Closet
wafflestudio20-5/team4-web pull request #63
Opened 2023-01-31 07:36 UTC by ksj-hikoo

2023-01-31 23:50 UTC, sukchan-0811 commented on src/components/Closet/ClosetBody/StyleList.tsx
> +      {styleList?.length !== 0 || !styleList ? (
여기 !styleList하면 styleList === null일 때 조건에 잡히지 않나요?

2023-01-31 23:50 UTC, sukchan-0811 commented on src/components/Closet/ClosetHeader/index.tsx
> +    }
팔로우/언팔로우와 관련해서, 로그인이 안 되어 있는 상태라면 그냥 해당 버튼을 렌더링하지 않는 게 더 깔끔하지 않을까요?

2023-01-31 23:50 UTC, sukchan-0811 commented on src/lib/api.ts
> +export const useApiUserStyleFecther = (id: number | null) => {
이거 헷갈릴 수도 있으니 style의 list를 가져온다는 걸 함수명에 명시하면 좋을 것 같습니다!

2023-01-31 23:50 UTC, sukchan-0811 commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
여기 setResult도 리턴하는 이유가 뭔가요?

2023-02-01 03:29 UTC, ksj-hikoo commented on src/components/Closet/ClosetHeader/index.tsx
> +    }
이 부분은 고민해봤는데  Header의 height 고정px가 아니라 반응형이라 버튼 자체를 렌더안할 시 헤더 layout이 얇아지고, 비어보이는 문제가 있습니다.
또, 생각해보면 어쨌든 커뮤니티 기능을 구현하고 있는 것이고 커뮤니티에서 적절한 로그인 유도는 괜찮지 않나합니다.
예를 들면, 원래 로그인 하지 않고 게시글을 보다가 댓글을 달려하면 '로그인 해주세요!' 하고 로그인페이지로 유도하는 것 정도는 합리적인 로그인 유도라고 생각이 되는데,
팔로우 팔로잉 버튼에 비로그인시 로그인페이지로 navigate하는 것도 같은 맥락에서 그렇게 억지스럽다는 느낌은 들지않고, layout측면에서 안정감이 생기기에 그냥 이렇게 구현했습니다.

2023-02-01 03:35 UTC, ksj-hikoo commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
팔로우, 언팔로우 이후 버튼이 바뀌는 리렌더를 일으키기 위해서
```
const FollowUser = (id: number, token: string | null) => {
    if (!token) {
      navigate('/login');
      return;
    }
    apiPostFollow(id, token)
      .then(() => {
        apiGetUser(id, token)
          .then((res) => {
            setResult((prev) => ({
              ...prev,
              data: res.data,
              error: undefined,
              loading: false,
            }));
          })
          .catch(() => {
            window.location.reload();
          });
      })
      .catch(() => {
        toast('다시 시도해주세요');
      });
  };
```
이렇게 코드를 짰습니다.
POST follow    then   GET user     then      setResult(response)    이렇게 흘러가서 팔로우,언팔로우 시 result state를 변화시키고 리렌더를 유도하기 위해 이렇게 짜봤는데 백엔드 api가 아직이라, 의도한대로 작동하는지는 모르겠습니다.

2023-02-01 04:12 UTC, sukchan-0811 commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
팔로우 이후의 리렌더를 위해서 user 전체를 다 가져오는 게 너무 비용이 큰 것 같기도 해서, 그냥 isFollowed를 컴포넌트에서 별도의 state로 관리하고 (default 값은 물론 서버에서 내려준 boolean이어야 합니다!) post follow 성공 시 setIsFollowed만 해주는 게 더 좋지 않을까 싶네요. 이 부분만의 리렌더를 위해서 useApiData 콜백의 리턴 값에 setResult를 추가할 필요는 없어보입니다...!

2023-02-01 06:55 UTC, dongjoocha commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
석찬 님 의견 좋은 것 같습니다. 팔로우/언팔로우 이후 바뀌는 건 팔로우/언팔로우 버튼 렌더링에 관련된 `isFollow`와 팔로워 수 렌더링에 관련된 `followingCount`밖에 없으므로 GET user 를 호출 후 새로고침 하는 것보다 `isFollow`, `followingCount`와 관련된 state 값만 조절해도 무방할 것 같습니다!

2023-02-01 07:30 UTC, dongjoocha commented
수고 정말 많으셨습니다! 방금 백이랑 연결해서 팔로우 기능 확인해보았는데 다음 사항들 확인 후 수정 부탁드립니다!

1. 홈화면의 스타일 프리뷰?에 있는 팔로우 버튼을 눌러도 아무 일도 일어나지 않습니다.
2. 옷장 페이지에서 팔로우 버튼 클릭 시 `accessToken`을 같이 보내지 않아 403 에러가 발생합니다. 원인을 찾아보니 `apiPostFollow`의 `axios.post`의 두 번째 인자로 header가 전달되어 header가 아닌 request body로 `Authorization ~`이 전달되고 있었습니다. 다음과 같이 수정 부탁드립니다.
```suggestion
export const apiPostFollow = (userId: number, token: string | null) =>
  axios.post<{}>(
    `/api/user/${userId}/follow`,
    {}, // 두 번째 인자로 빈 request body 전달
    {
      headers: token ? auth(token) : undefined,
    }
  );
```
3. 지금은 어떤 유저가 인스타 아이디를 지정하지 않았을 시 인스타 버튼을 눌러도 아무 일도 일어나지 않는 것 같습니다. 인스타 아이디가 없는 경우 해당 버튼을 아예 렌더링하지 않는 게 더 좋을 것 같습니다..! 혹은 toast로 아직 해당 유저는 인스타 아이디를 지정하지 않았다는 메시지를 띄워도 괜찮을 것 같습니다.

2023-02-01 09:20 UTC, hitkoo commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
Home follow를 까먹고있었는데 그거 구현하는 김에 석찬님 말씀대로 follow만 boolean state로 관리하도록 구현해보겠습니다. @dongjoocha 혹시 지금 백 메인에 POST/DELETE follow merge됐을까요?

2023-02-01 09:34 UTC, dongjoocha commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
@ksj-hikoo 아뇨 아직 PR 올리기 전입니다. push는 해두었으니 `follow` 브랜치 pull 받아서 테스트해보실 수 있습니다!

2023-02-01 10:02 UTC, dongjoocha commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
@ksj-hikoo 팔로워/팔로잉 목록 관련 API도 구현 완료 후 push 해두었습니다! 끝에 s 붙이는 등 수정한 사항이 조금 있으니 Notion 확인 후 구현해주시면 되겠습니다.

2023-02-01 11:00 UTC, dongjoocha commented on src/lib/api.ts
> +  return { data, loading, error, setResult };
@ksj-hikoo 유저 검색 관련 API도 구현 완료 후 push 해두었습니다!

2023-02-01 17:44 UTC, sukchan-0811 requested changes
다른 회원의 옷장을 구경할 때에도 `회원정보변경` 버튼이 활성화 돼있던데, 이 부분 수정 필요할 것 같습니다!

2023-02-02 04:21 UTC, merged