Create Homepage ProtoType
wafflestudio20-5/team4-web pull request #8
Opened 2022-12-28 15:39 UTC by ksj-hikoo

외적인거 버튼누르면 나오는 SideCategorybar빼고 전부 구현

기능은 selectedCategory state 구현완료 하지만 useApiItemListFetcher() 에 값을 넣었을 때 해당 category data만 받아오지 않음
(mock-up data에 optional 구현하는 건 오바인 것 같고, 추후 백엔드랑 연결할 때 구현하면 될 듯)

min-width 설정 안한거로 세미나5때 피드백 많이 받았어서, 한다고 해봤는데 잘한지는 모르겠습니다.

2022-12-29 07:15 UTC, sukchan-0811 requested changes

2022-12-29 07:15 UTC, sukchanlee1 commented on src/types.d.ts
> +declare module '*.svg' {
이거 svg는 그냥 `declare module '*.svg';` 하면 안 되나요?

2022-12-29 07:15 UTC, sukchanlee1 commented on src/components/Home/index.tsx
> +import ItemList from './itemList';
컴포넌트 이름 `ItemList`(대문자로 시작)이어서 오류 발생하는데 아예 통일성을 위해 모든 컴포넌트 이름은 Pascal Case로 가시죠

2022-12-29 07:15 UTC, sukchanlee1 commented on src/types.d.ts
> +declare module '*.svg' {
이거 직접 해보니까 그냥 저렇게 선언해도 되네요

2022-12-29 07:15 UTC, sukchanlee1 commented on src/components/Home/index.tsx
> +import OpenCateGoryButton from '../../resources/asset/menu.svg';
같은 맥락에서 이건 컴포넌트가 아니니까 `toggle-buttton`처럼 이름 짓는 게 좋을 것 같다는 개인적인 의견이 있습니다

2022-12-29 07:15 UTC, sukchanlee1 commented on src/components/Home/index.tsx
>    const [openCategorySideBar, setopenCategorySideBar] = useState(false);
이거 (코멘트 위치가 제대로 지정이 안 된 것 같긴 한데) 함수 이름 handle 말고 toggle로 하는 게 어떨까요?

2022-12-29 07:15 UTC, sukchanlee1 commented on src/components/Home/index.tsx
>    const [openCategorySideBar, setopenCategorySideBar] = useState(false);
`handleCategorySideBar` -> `toggleCategorySideBar` 얘기한 겁니다

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/ItemList.tsx
> +export function ItemListCategory({
굳이 외부에서 안 쓸 컴포넌트는 export 안 하는 게 좋을 것 같습니다!

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/ItemList.tsx
> +          <button
사소한 거긴 한데 버튼에 `cursor: pointer` 스타일 지정해주면 좋을 것 같습니다!

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/itemPreview.tsx
> +export default function ItemPreview({ item, idx }: ItemPreviewProps) {
라벨 표시도 만들어주시면 좋을 것 같습니다!

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/itemPreview.tsx
> +      <div className={styles.name}>{item.name}</div>
무신사 홈페이지는 상품명 길면 자르고 '...' 붙이던데 이것도 구현하면 좋을 것 같습니다!

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/itemPreview.tsx
> +            <span className={styles.oldPrcie}>
사소한 오타... Price로 바꿔주시면 좋을 것 같습니다

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/itemPreview.tsx
> +              {item.oldPrice.toLocaleString()}원
👍

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/itemPreview.tsx
> +      <div className={styles.rank}>{idx + 1}위</div>
👍

2022-12-29 07:15 UTC, sukchan-0811 commented on src/components/Home/itemPreview.tsx
> +            <span className={styles.oldPrcie}>
아니면 이거 스타일명 헷갈리니까 `realPrice`랑 `crossedOutPrice`로 구분하는 것도 좋을 것 같습니다...

2022-12-29 07:44 UTC, ksj-hikoo commented on src/components/Home/ItemList.tsx
> +          <button
이건 밑에 전체/상의/아우터/바지/스커트 등은 클릭했을 때 기능이 있는데 상품탭은 hover는 되는데 눌러도 아무 변화가 없어서 임의로 hover설정안 했습니다!
밑에 카테고리들에는 hover cursor:poiner, text-decoration: underline 설정 추가했습니다.

2022-12-29 07:50 UTC, ksj-hikoo commented on src/components/Home/index.tsx
> +import ItemList from './itemList';
새벽에 파일명 무지성 복붙으로 하다가 이런 실수를 했네용;; 반영했습니다.

2022-12-30 13:23 UTC, sukchan-0811 requested changes
일단 `displayCategoryinCamelCase`가 하는 역할이 카테고리 string을 카멜 케이스로 바꿔주는 것이 아니라 그냥 첫 글자만 capitalize하는 것으로 보입니다... 이는 간단하게 자바스크립트로 구현할 수 있는 로직이라서 따로 function을 두는 것보다 HomePage 컴포넌트 내에서 해결하는 것이 더 좋아 보입니다...!

2022-12-30 13:23 UTC, sukchanlee1 commented on src/App.js
> +import HomePage from './components/Home/Index';
이건 그냥 Home이라는 디렉토리에서 index.tsx를 자동으로 지칭하는 거라서 `./components/Home`으로 그대로 놔두셔야 할 것 같습니다!

2022-12-30 13:23 UTC, sukchanlee1 commented on src/App.js
> +import HomePage from './components/Home/Index';
`itemList.module.css`, `itemPreview.module.css`, `itemPreview.tsx`만 (파일명에서) 첫 글자 대문자로 바꿔주시면 될 것 같습니다.

2022-12-31 13:46 UTC, sukchan-0811 approved these changes
좋은 것 같습니다!

2023-01-02 08:49 UTC, merged